import type { Metadata } from "next";
import "./globals.css";
import Navbar from "./ui/navbar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`antialiased dm-serif-text-regular`}
      >

        <main className="min-h-screen">
          <Navbar/>
        {children}
        </main>
      </body>
    </html>
  );
}
